adding different action (#24) (#25)
(cherry picked from commit 56a0bdf463a9986022191d0cc239bcf2b769207d)

Co-authored-by: ausias-armesto <ausiasarmesto@gmail.com>

diff --git a/.github/workflows/backport.yml b/.github/workflows/backport.yml
--- a/.github/workflows/backport.yml
+++ b/.github/workflows/backport.yml
@@ -1,36 +1,63 @@
 name: Backport PR
 on:
   pull_request_target:
-    branches:
-      - master
-    types: 
+    types:
       - closed
+      - labeled
 
 jobs:
   backport:
     name: Backport PR
     runs-on: ubuntu-latest
+    # Only react to merged PRs for security reasons.
+    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
     if: |
-      github.event.pull_request.merged == true
-      && ! contains(github.event.pull_request.labels.*.name, 'skip-backport')
+      github.event.pull_request.merged && (
+        github.event.action == 'closed'
+        || (
+          github.event.action == 'labeled'
+          && contains(github.event.label.name, 'backport')
+        )
+      )
     steps:
-      - name: Checkout hoprnet repository
-        uses: actions/checkout@v3
-
-      - name: Fetch
-        run: |
-          git fetch --all
-
-      - name: Backport Action
-        uses: sqren/backport-github-action@v8.9.3
+      - uses: tibdex/backport@v2
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          auto_backport_label_prefix: backport-to-
 
-      - name: Info log
-        if: ${{ success() }}
-        run: cat ~/.backport/backport.info.log
+
+# name: Backport PR
+# on:
+#   pull_request_target:
+#     branches:
+#       - master
+#     types: 
+#       - closed
+
+# jobs:
+#   backport:
+#     name: Backport PR
+#     runs-on: ubuntu-latest
+#     if: |
+#       github.event.pull_request.merged == true
+#       && ! contains(github.event.pull_request.labels.*.name, 'skip-backport')
+#     steps:
+#       - name: Checkout hoprnet repository
+#         uses: actions/checkout@v3
+
+#       - name: Fetch
+#         run: |
+#           git fetch --all
+
+#       - name: Backport Action
+#         uses: sqren/backport-github-action@v8.9.3
+#         with:
+#           github_token: ${{ secrets.GITHUB_TOKEN }}
+#           auto_backport_label_prefix: backport-to-
+
+#       - name: Info log
+#         if: ${{ success() }}
+#         run: cat ~/.backport/backport.info.log
         
-      - name: Debug log
-        if: ${{ failure() }}
-        run: cat ~/.backport/backport.debug.log
+#       - name: Debug log
+#         if: ${{ failure() }}
+#         run: cat ~/.backport/backport.debug.log
